% Script file for Swirly debugger
% Automatically executed!
% ** Each line must be terminated with a newline **

%%% set the path to where the subdir images/ is located 
path /home/suike/swirly/main/images/

%%% three file formats recognized: .srec .elf .bin (defaults to .bin)

%%% boot image is always from a0000000 to a0200000
l ../fakebootrom/fbr.srec 

l IP.BIN 8c008000

%l ta.srec
%l videotest.srec
%l mapletest.srec
%l stars.srec 

